import React, { useState } from 'react';
import { Octokit } from '@octokit/rest';
import { useStore } from '../store/useStore';
import { X, Github, Loader2, CheckCircle } from 'lucide-react';

interface DeployModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function DeployModal({ isOpen, onClose }: DeployModalProps) {
  const { markdown, theme } = useStore();
  const [token, setToken] = useState('');
  const [repoName, setRepoName] = useState('my-dev-portfolio');
  const [status, setStatus] = useState<'idle' | 'deploying' | 'success' | 'error'>('idle');
  const [errorMsg, setErrorMsg] = useState('');
  const [deployedUrl, setDeployedUrl] = useState('');

  if (!isOpen) return null;

  const handleDeploy = async () => {
    if (!token || !repoName) {
      setErrorMsg('Token and Repository Name are required.');
      setStatus('error');
      return;
    }

    setStatus('deploying');
    setErrorMsg('');

    try {
      const octokit = new Octokit({ auth: token });
      
      // 1. Get user
      const { data: user } = await octokit.rest.users.getAuthenticated();

      // 2. Create repo
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'Portfolio generated by DevPortfolio AI',
        auto_init: true,
      });

      // 3. Create index.html content
      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      body { font-family: system-ui, -apple-system, sans-serif; }
      .theme-dark { background: #0a0a0a; color: #f5f5f5; }
      .theme-neon { background: #000; color: #4ade80; font-family: monospace; }
      .theme-glassmorphism { background: linear-gradient(to bottom right, #6366f1, #a855f7, #ec4899); color: white; }
      .theme-minimal { background: #ffffff; color: #111827; }
    </style>
</head>
<body class="theme-${theme}">
    <div id="root">
      <div class="max-w-4xl mx-auto p-8">
        <h1 class="text-4xl font-bold mb-8">Portfolio Exported</h1>
        <p>Your portfolio has been exported successfully.</p>
        <pre class="mt-8 p-4 bg-black/10 rounded overflow-auto">${markdown}</pre>
      </div>
    </div>
</body>
</html>`;

      // 4. Push file
      await octokit.rest.repos.createOrUpdateFileContents({
        owner: user.login,
        repo: repoName,
        path: 'index.html',
        message: 'Initial commit from DevPortfolio AI',
        content: btoa(unescape(encodeURIComponent(htmlContent))),
      });

      // 5. Enable Pages
      await octokit.rest.repos.createPagesSite({
        owner: user.login,
        repo: repoName,
        source: {
          branch: 'main',
          path: '/',
        },
      });

      setDeployedUrl(`https://${user.login}.github.io/${repoName}/`);
      setStatus('success');
    } catch (error: any) {
      console.error(error);
      setErrorMsg(error.message || 'An error occurred during deployment.');
      setStatus('error');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="bg-gray-900 border border-gray-800 rounded-2xl w-full max-w-md p-6 shadow-2xl relative">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center">
            <Github className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Deploy to GitHub Pages</h2>
            <p className="text-sm text-gray-400">Publish your portfolio instantly.</p>
          </div>
        </div>

        {status === 'success' ? (
          <div className="text-center py-8 space-y-4">
            <div className="w-16 h-16 bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
              <CheckCircle className="w-8 h-8 text-green-500" />
            </div>
            <h3 className="text-xl font-bold text-white">Deployment Started!</h3>
            <p className="text-gray-400 text-sm">
              GitHub Pages is building your site. It may take a minute or two to go live.
            </p>
            <a 
              href={deployedUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="inline-block mt-4 text-indigo-400 hover:text-indigo-300 font-medium"
            >
              {deployedUrl}
            </a>
          </div>
        ) : (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1">
                GitHub Personal Access Token
              </label>
              <input
                type="password"
                value={token}
                onChange={(e) => setToken(e.target.value)}
                placeholder="ghp_xxxxxxxxxxxx"
                className="w-full bg-gray-950 border border-gray-800 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all"
              />
              <p className="text-xs text-gray-500 mt-1">
                Needs 'repo' and 'workflow' scopes. We don't store this.
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1">
                Repository Name
              </label>
              <input
                type="text"
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                className="w-full bg-gray-950 border border-gray-800 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all"
              />
            </div>

            {status === 'error' && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm">
                {errorMsg}
              </div>
            )}

            <button
              onClick={handleDeploy}
              disabled={status === 'deploying'}
              className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2.5 rounded-lg transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed mt-6"
            >
              {status === 'deploying' ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Deploying...
                </>
              ) : (
                'Deploy Now'
              )}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
