import React, { useState } from 'react';
import { useStore, Theme } from '../store/useStore';
import { Download, Layout, Palette, Code, Eye, Rocket } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import DeployModal from './DeployModal';
import { ShinyText } from './ShinyText';

export default function Toolbar() {
  const { theme, setTheme, markdown } = useStore();
  const [isDeployModalOpen, setIsDeployModalOpen] = useState(false);

  const themes: { id: Theme; label: string }[] = [
    { id: 'minimal', label: 'Minimal' },
    { id: 'glassmorphism', label: 'Glassmorphism' },
    { id: 'neon', label: 'Neon Cyberpunk' },
    { id: 'dark', label: 'Dark Developer' },
  ];

  const handleExport = async () => {
    const zip = new JSZip();
    
    // Add index.html
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      body { font-family: system-ui, -apple-system, sans-serif; }
      .theme-dark { background: #0a0a0a; color: #f5f5f5; }
      .theme-neon { background: #000; color: #4ade80; font-family: monospace; }
      .theme-glassmorphism { background: linear-gradient(to bottom right, #6366f1, #a855f7, #ec4899); color: white; }
      .theme-minimal { background: #ffffff; color: #111827; }
    </style>
</head>
<body class="theme-${theme}">
    <div id="root">
      <!-- Content generated by DevPortfolio AI -->
      <div class="max-w-4xl mx-auto p-8">
        <h1 class="text-4xl font-bold mb-8">Portfolio Exported</h1>
        <p>Your portfolio has been exported successfully. To view the full interactive version, you need to run a build process or deploy it.</p>
        <pre class="mt-8 p-4 bg-black/10 rounded overflow-auto">${markdown}</pre>
      </div>
    </div>
</body>
</html>`;

    zip.file("index.html", htmlContent);
    zip.file("resume.md", markdown);
    
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, "devportfolio-export.zip");
  };

  return (
    <>
      <div className="h-14 bg-gray-900 border-b border-gray-800 flex items-center justify-between px-4 sm:px-6 text-gray-300">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
            <Code className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-white tracking-tight hidden sm:block">
            <ShinyText text="DevPortfolio" /> <span className="text-indigo-400">AI</span>
          </span>
        </div>

        <div className="flex items-center gap-3 sm:gap-6">
          <div className="hidden lg:flex items-center gap-3 bg-gray-800/50 px-3 py-1.5 rounded-full border border-gray-700/50">
            <Palette className="w-4 h-4 text-gray-400" />
            <div className="flex gap-1">
              {themes.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setTheme(t.id)}
                  className={`px-3 py-1 text-xs font-medium rounded-full transition-all ${
                    theme === t.id 
                      ? 'bg-indigo-500 text-white shadow-md shadow-indigo-500/20' 
                      : 'text-gray-400 hover:text-gray-200 hover:bg-gray-700'
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleExport}
              className="flex items-center gap-2 bg-gray-800 text-gray-300 hover:bg-gray-700 hover:text-white px-3 sm:px-4 py-1.5 rounded-full text-sm font-semibold transition-colors border border-gray-700"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Export</span>
            </button>
            <button
              onClick={() => setIsDeployModalOpen(true)}
              className="flex items-center gap-2 bg-white text-gray-900 hover:bg-gray-100 px-3 sm:px-4 py-1.5 rounded-full text-sm font-semibold transition-colors shadow-lg shadow-white/10"
            >
              <Rocket className="w-4 h-4" />
              <span className="hidden sm:inline">Deploy</span>
            </button>
          </div>
        </div>
      </div>
      
      <DeployModal 
        isOpen={isDeployModalOpen} 
        onClose={() => setIsDeployModalOpen(false)} 
      />
    </>
  );
}
